var x = 3
const y = 0

try{

    y = 1
    
    console.log(x / y)
}catch(err){
    console.log(err)
}
console.log('Fim')